version: '3.9'

services:
  backend:
    build: ./backend
    container_name: node-app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo_db
    depends_on:
      - mongo

  tasks-manager:
    build: ./tasks-manager
    container_name: angular-app
    ports:
      - "4200:4200"
    volumes:
      - ./tasks-manager:/usr/src/app
    depends_on:
      - backend

  mongo:
    image: mongo:8.2.2
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
